# Generated by Django 3.0.4 on 2020-03-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_supervisor', models.CharField(max_length=50, verbose_name='Дипломный руководитель')),
                ('theme_name', models.CharField(max_length=300, verbose_name='Название темы')),
                ('free_place', models.SmallIntegerField(verbose_name='Свободные места')),
                ('sign_up', models.BooleanField(verbose_name='Запись')),
            ],
        ),
    ]
