# Generated by Django 3.0.4 on 2020-03-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема ВКР', 'verbose_name_plural': 'Темы ВКР'},
        ),
    ]
