# Generated by Django 3.0.4 on 2020-03-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0003_remove_theme_sign_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО студента')),
                ('group', models.CharField(max_length=10, verbose_name='Группа студента')),
                ('acadPerf', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='theme_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='theme_supervisor',
            new_name='supervisor',
        ),
    ]
