# Generated by Django 3.0.4 on 2020-03-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0004_auto_20200314_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='name',
            new_name='subject',
        ),
    ]
