# Generated by Django 3.0.4 on 2020-04-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0005_auto_20200314_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=50, verbose_name='ФИО научного руководителя:')),
            ],
            options={
                'verbose_name': 'Научный руководитель',
                'verbose_name_plural': 'Научные руководители',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='ФИО студента:')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regvkr.ScientificDirector')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=300, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема ВКР',
                'verbose_name_plural': 'Темы ВКР',
            },
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='scientificdirector',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regvkr.Topic'),
        ),
    ]
