# Generated by Django 3.0.4 on 2020-04-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0006_auto_20200418_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='director',
        ),
        migrations.DeleteModel(
            name='ScientificDirector',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
