# Generated by Django 3.0.4 on 2020-04-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regvkr', '0007_auto_20200427_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('PND', 'Заявка в рассмотрении'), ('RJD', 'Заявка отклонена'), ('ACD', 'Заявка принята')], default='PND', max_length=20, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
        migrations.CreateModel(
            name='ScientificDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_D', models.CharField(max_length=15, verbose_name='Имя научного руководителя:')),
                ('last_name_D', models.CharField(max_length=25, verbose_name='Фамилия научного руководителя:')),
                ('patronymic_D', models.CharField(max_length=25, null=True, verbose_name='Отчество научного руководителя')),
                ('director_login', models.CharField(max_length=254, unique=True, verbose_name='Логин преподавателя:')),
                ('director_password', models.CharField(max_length=32, verbose_name='Пароль:')),
            ],
            options={
                'verbose_name': 'Научный руководитель',
                'verbose_name_plural': 'Научные руководители',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_S', models.CharField(max_length=15, verbose_name='Имя студента:')),
                ('last_name_S', models.CharField(max_length=25, verbose_name='Фамилия студента:')),
                ('student_login', models.CharField(max_length=254, unique=True, verbose_name='Логин студента:')),
                ('student_password', models.CharField(max_length=32, verbose_name='Пароль:')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Электронная почта студента:')),
                ('student_num', models.PositiveIntegerField(unique=True, verbose_name='Номер зачётной книжки:')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=300, verbose_name='Название темы:')),
                ('director_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regvkr.ScientificDirector')),
            ],
            options={
                'verbose_name': 'Тема ВКР',
                'verbose_name_plural': 'Темы ВКР',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regvkr.ApplicationStatus')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regvkr.Student')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regvkr.Topic')),
            ],
            options={
                'verbose_name': 'Дата заявки',
                'verbose_name_plural': 'Даты заявок',
            },
        ),
    ]
