# Generated by Django 3.0.4 on 2020-05-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0008_application_applicationstatus_scientificdirector_student_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regvkr.ApplicationStatus'),
        ),
    ]
