# Generated by Django 3.0.4 on 2020-05-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0009_auto_20200508_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificDirector1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_D', models.CharField(max_length=15, verbose_name='Имя научного руководителя:')),
                ('last_name_D', models.CharField(max_length=25, verbose_name='Фамилия научного руководителя:')),
                ('patronymic', models.CharField(max_length=25, null=True, verbose_name='Отчество научного руководителя')),
            ],
            options={
                'verbose_name': 'Научный руководитель',
                'verbose_name_plural': 'Научные руководители',
                'ordering': ['last_name_D'],
            },
        ),
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_S', models.CharField(max_length=15, verbose_name='Имя студента:')),
                ('last_name_S', models.CharField(max_length=25, verbose_name='Фамилия студента:')),
                ('num', models.PositiveIntegerField(unique=True, verbose_name='Номер зачётной книжки:')),
                ('group', models.CharField(max_length=8, verbose_name='Группа:')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name_S'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['created_at'], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['director_id'], 'verbose_name': 'Тема ВКР', 'verbose_name_plural': 'Темы ВКР'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='status_id',
        ),
        migrations.AddField(
            model_name='application',
            name='status_name',
            field=models.CharField(choices=[('1', 'Заявка в рассмотрении'), ('2', 'Заявка отклонена'), ('3', 'Заявка принята')], default='1', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
        migrations.AlterField(
            model_name='application',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regvkr.Student1'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='director_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regvkr.ScientificDirector1'),
        ),
        migrations.DeleteModel(
            name='ScientificDirector',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
