# Generated by Django 3.0.4 on 2020-05-14 23:13

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('regvkr', '0010_auto_20200515_0212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScientificDirector1',
            new_name='ScientificDirector',
        ),
        migrations.RenameModel(
            old_name='Student1',
            new_name='Student',
        ),
    ]
