# Generated by Django 3.0.4 on 2020-05-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0011_auto_20200515_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificdirector',
            name='position_name',
            field=models.CharField(choices=[('1', 'ассистент'), ('2', 'старший преподаватель'), ('3', 'доцент'), ('4', 'профессор'), ('5', 'зав.каф')], default='', max_length=22, verbose_name='Должность:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status_name',
            field=models.CharField(choices=[('1', 'Заявка в рассмотрении'), ('2', 'Заявка отклонена'), ('3', 'Заявка принята')], default='1', max_length=20, verbose_name='Статус заявки:'),
        ),
    ]
