# Generated by Django 3.0.4 on 2020-05-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0012_auto_20200515_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificdirector',
            name='position_name',
            field=models.CharField(choices=[('1', 'ассистент'), ('2', 'старший преподаватель'), ('3', 'доцент'), ('4', 'профессор'), ('5', 'зав.каф')], default='1', max_length=22, verbose_name='Должность:'),
        ),
    ]
