# Generated by Django 3.0.4 on 2020-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0013_auto_20200515_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificdirector',
            name='first_name_D',
            field=models.CharField(max_length=15, verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='scientificdirector',
            name='last_name_D',
            field=models.CharField(max_length=25, verbose_name='Фамилия:'),
        ),
        migrations.AlterField(
            model_name='scientificdirector',
            name='patronymic',
            field=models.CharField(max_length=25, null=True, verbose_name='Отчество:'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name_S',
            field=models.CharField(max_length=15, verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name_S',
            field=models.CharField(max_length=25, verbose_name='Фамилия:'),
        ),
    ]
