# Generated by Django 3.0.4 on 2020-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0014_auto_20200516_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientificdirector',
            options={'ordering': ['last_name'], 'verbose_name': 'Научный руководитель', 'verbose_name_plural': 'Научные руководители'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.RemoveField(
            model_name='scientificdirector',
            name='first_name_D',
        ),
        migrations.RemoveField(
            model_name='scientificdirector',
            name='last_name_D',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name_S',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name_S',
        ),
        migrations.AddField(
            model_name='scientificdirector',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=255, verbose_name='Логин:'),
        ),
        migrations.AddField(
            model_name='scientificdirector',
            name='first_name',
            field=models.CharField(default='test', max_length=15, verbose_name='Имя:'),
        ),
        migrations.AddField(
            model_name='scientificdirector',
            name='last_name',
            field=models.CharField(default='test', max_length=25, verbose_name='Фамилия:'),
        ),
        migrations.AddField(
            model_name='scientificdirector',
            name='password',
            field=models.CharField(default='test', max_length=32, verbose_name='Пароль:'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='test', max_length=15, verbose_name='Имя:'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='test', max_length=25, verbose_name='Фамилия:'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='test', max_length=32, verbose_name='Пароль:'),
        ),
    ]
