# Generated by Django 3.0.4 on 2020-05-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0016_auto_20200518_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificdirector',
            name='is_director',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.AddField(
            model_name='scientificdirector',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scientificdirector',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Логин/почта'),
        ),
    ]
