# Generated by Django 3.0.4 on 2020-05-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regvkr', '0017_auto_20200518_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='num',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер зачётной книжки:'),
        ),
    ]
