# Generated by Django 3.0.4 on 2020-05-18 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regvkr', '0018_auto_20200518_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientificdirector',
            options={'verbose_name': 'Научный руководитель', 'verbose_name_plural': 'Научные руководители'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.RemoveField(
            model_name='scientificdirector',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scientificdirector',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='scientificdirector',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='scientificdirector',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='scientificdirector',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='scientificdirector',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_director',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='scientificdirector',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scientificdirector',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='num',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер зачётной книжки:'),
        ),
    ]
